Onboarding MSI for daily autogen
Azure/azure-resource-manager-schemas pull request #2445
Opened 2022-06-29 08:52 UTC by serhangursoy-microsoft

2022-06-29 18:08 UTC, jorgecotillo approved these changes

2022-06-29 18:08 UTC, jorgecotillo commented on schemas/2015-08-31-preview/Microsoft.ManagedIdentity.json
> -        "name": {
Are these updates result of running https://github.com/Azure/azure-resource-manager-schemas/actions/workflows/generate-types.yml on your branch?

2022-06-29 18:08 UTC, jorgecotillo commented on schemas/2015-08-31-preview/Microsoft.ManagedIdentity.json
> -        "name": {
nvm, it is.

2022-06-29 18:11 UTC, jorgecotillo requested changes
Can you please the tests locally,, seems like your update is breaking existing tests: https://github.com/Azure/azure-resource-manager-schemas#runing-unit-tests

2022-06-30 09:19 UTC, serhangursoy-microsoft commented
Updated the PR. Changed/updated existing test cases. And added two more for newly generated versions. 
Tested locally now - seems to be working as expected

2022-07-01 01:02 UTC, jorgecotillo approved these changes

2022-07-01 01:02 UTC, merged