Add AKS 2023-08 ARM schemas
Azure/azure-resource-manager-schemas pull request #2984
Opened 2023-10-17 09:18 UTC by FumingZhang

Manually generated these the ARM schemas for AKS based on 2023-08-01 and 2023-08-02-preview swagger specs. To bypass the path issues, the directory structure under namespace Microsoft.ContainerService was modified as in [PR #26256](https://github.com/Azure/azure-rest-api-specs/pull/26256).
```
autorest --version=3.0.6374 --use=@autorest/azureresourceschema@3.0.109 --azureresourceschema --output-folder=/home/fumingzhang/azure-resource-manager-schemas/schemas --pass-thru:subset-reducer --pass-thru:schema-validator-swagger --tag=package-2023-08 /home/fumingzhang/azure-rest-api-specs/specification/containerservice/resource-manager/readme.md
autorest --version=3.0.6374 --use=@autorest/azureresourceschema@3.0.109 --azureresourceschema --output-folder=/home/fumingzhang/azure-resource-manager-schemas/schemas --pass-thru:subset-reducer --pass-thru:schema-validator-swagger --tag=package-preview-2023-08 /home/fumingzhang/azure-rest-api-specs/specification/containerservice/resource-manager/readme.md
```

![image](https://github.com/Azure/azure-resource-manager-schemas/assets/81607949/0e603053-6c94-4b93-8c9c-49cb1d3df013)

2023-10-17 12:31 UTC, anthony-c-martin commented
Please add `disabledForAutogen: true` here:
https://github.com/Azure/azure-resource-manager-schemas/blob/2bafa648140ece85a50e9aa57c0811be8923a1b4/generator/autogenlist.ts#L371C49-L371C49

And add a `$ref` for each resource type to:
https://github.com/Azure/azure-resource-manager-schemas/blob/2bafa648140ece85a50e9aa57c0811be8923a1b4/schemas/2019-04-01/deploymentTemplate.json#L667

2023-10-17 12:32 UTC, anthony-c-martin requested changes
See comment

2023-10-18 05:50 UTC, FumingZhang commented
> See comment

Comments resolved

2023-10-18 08:08 UTC, anthony-c-martin approved these changes

2023-10-18 08:08 UTC, merged